### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by thawri1** [tluck/Dell-M4800-Clover#2]
can you please tell me how to use this.
why EFI content is not complete?
for example config.plist is not exist.
I used EFI of this link:
https://www.tonymacx86.com/attachments/efi-zip.471692/
that found it in this link:
https://www.tonymacx86.com/threads/success-installed-catalina-10-15-3-on-dell-m4800-but-no-audio.292071/

but stuck on installing
then I use your EFI folder but because of some files does not exist, I copy your files and merge by another EFI. now its seems all things is working except sound
can you help me, please?

**Comment by tluck** [comment]
what is missing? look in the OEM/0V5GVY directory/folder for files specific to my model. you can move those files to EFI/CLOVER if that makes it more clear. there is config.plist in the OEM/0V5GVY directory. the config.plist is using layout 18 with AppleALC.kext in codec alc292

**Comment by thawri1** [comment]
thanks for your reply.
my laptop model is Dell m4800 i7 4910 k2100m. if I make an installer usb and mount EFI partition then delete "EFI" folder in it, then copy your EFI folder in usb EFI partition (without any other file), it should works?

**Comment by tluck** [comment]
my systems is AMD gfx. so there would be some changes for your Nvidia card. OSXLatitude.com has some great M4800 threads especially with alternate HW configurations.
